Restricted scrolling beyond the first and last workspaces and fixed bug with Sidebar Switches Multiple Spaces Instead of One
zen-browser/desktop pull request #3217
Opened 2024-11-26 23:11 UTC by neurokitti

I fixed this bug https://github.com/zen-browser/desktop/issues/3162

I made is to that if you keep swiping at the end of a workspace it no longer just wraps around

2024-11-27 17:44 UTC, kristijanribaric requested changes

2024-11-27 17:44 UTC, kristijanribaric commented on src/browser/base/zen-components/ZenWorkspaces.mjs
Can you remove all the unnecessarily added empty rows?

2024-11-27 21:22 UTC, neurokitti commented on src/browser/base/zen-components/ZenWorkspaces.mjs
this should work hopefully

2024-11-28 17:54 UTC, mr-cheffy commented
Ready for merge? @neurokitti

2024-11-28 18:03 UTC, neurokitti commented
Should be. I haven't been able to test the prefs because my zen install is still having the patch issue

2024-11-28 20:00 UTC, neurokitti commented
I'm going to do more testing

2024-11-28 20:00 UTC, closed without merging