Fix something I forgot
zen-browser/desktop pull request #3292
Opened 2024-11-29 10:21 UTC by larziwau

Fix something I forgot in the build ci. I'm unsure if i should upgrade sccache though
Also update Python

2024-11-29 16:40 UTC, larziwau commented
tried a fix for the update submodule thingy

2024-12-01 18:34 UTC, mr-cheffy requested changes

2024-12-01 18:34 UTC, mr-cheffy commented on .github/workflows/build.yml
> +          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
What's this for?

2024-12-02 10:05 UTC, larziwau commented on .github/workflows/build.yml
> +          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
well its documented in the actions/checkout repo, this is the official email of actions bot

2024-12-02 16:54 UTC, chenasraf commented on .github/workflows/build.yml
> +          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
I was curious so I looked it up, it's correct, that's the proper attached user id for github actions bot,

See:
- https://github.com/actions/checkout/pull/1707
- https://api.github.com/users/github-actions%5Bbot%5D

2024-12-03 10:09 UTC, larziwau commented on .github/workflows/build.yml
> +          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
yes, this is why i made this pr

2024-12-13 10:13 UTC, larziwau commented
anyways is there anything about the pr?

2024-12-13 10:14 UTC, closed without merging