Feature: Add toggle to disable new tab on double click
zen-browser/desktop pull request #3392
Opened 2024-12-05 01:15 UTC by vintydong

Added preference to toggle opening new tab on double click in sidebar

- Default: Enabled
- When enabled, same behavior as current build (open new tab)
- When disabled, maximize window

https://github.com/user-attachments/assets/36762bbb-0c77-4693-97e0-8397b73f03c9

2024-12-12 12:41 UTC, mr-cheffy requested changes

2024-12-12 12:41 UTC, mr-cheffy commented on src/browser/app/profile/zen-browser.js
> +pref("zen.tabs.openNewTabByDblclick", true);
Thanks!

But could this be renamed to `zen.tabs.open-new-tab-by-dblclick`

2024-12-15 23:45 UTC, vintydong commented on src/browser/app/profile/zen-browser.js
> +pref("zen.tabs.openNewTabByDblclick", true);
Made changes locally but running into issues after 133.0.3 in rebuilding and running local. Will try to reinstall and rebuild if I can't find a solution

2025-05-29 10:25 UTC, Veri7ion commented
Please

2025-05-29 15:46 UTC, mr-cheffy commented
Sorry, there are some git conflicts

2025-08-28 08:47 UTC, closed without merging