Shortcuts for Tab Navigation Prev/Next
zen-browser/desktop pull request #3599
Opened 2024-12-11 19:52 UTC by normaltaro

Added 2 shortcuts for tab navigation.
1. Switching to Next Tab (Unbounded by default)
2. Switching to Previous Tab (Unbounded by default)

Relevant Issue: https://github.com/zen-browser/desktop/issues/1678

I know English. Do I also need to submit a PR to the I10n repository for this to be functional?

2024-12-12 12:38 UTC, mr-cheffy commented
Great!

But we'll need to disable the other shortcuts.. Ill do that when I get home and ill merge

2024-12-12 12:40 UTC, mr-cheffy requested changes
Could you update `LATEST_KBS_VERSION`?

2024-12-12 14:06 UTC, normaltaro commented
done

2024-12-16 16:36 UTC, normaltaro commented
do i move LATEST_KBS_VERSION to 6?

2025-01-13 02:20 UTC, goosethedev commented
Any updates on this? :eyes:

2025-01-13 20:02 UTC, mauro-balades commented
> Any updates on this? 👀

This ended up being not as easy as it looks... Im still investigating

2025-01-22 18:39 UTC, KorigamiK commented
If anyone wants a workaround to get this feature you can try out my hotkeys config in the meantime which works good for me:

https://github.com/KorigamiK/zen-conf/blob/main/chrome/JS/hotkeys.uc.js

2025-01-22 21:16 UTC, Esyriz commented
> If anyone wants a workaround to get this feature you can try out my hotkeys config in the meantime which works good for me:
> 
> https://github.com/KorigamiK/zen-conf/blob/main/chrome/JS/hotkeys.uc.js

I wasn't able to make this work but I used karabiner elements complex modifications instead to bind the keys i wanted to ctrl+tab and ctrl+shift+tab

```
{
    "description": "next/previoustab",
    "manipulators": [
        {
            "from": { "key_code": "f2" },
            "to": [
                {
                    "key_code": "tab",
                    "modifiers": "control"
                }
            ],
            "type": "basic"
        },
        {
            "from": { "key_code": "f1" },
            "to": [
                {
                    "key_code": "tab",
                    "modifiers": ["shift", "control"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

2025-01-22 21:29 UTC, KorigamiK commented
> I wasn't able to make this work but I used karabiner elements complex modifications instead to bind the keys 

Ah, nice although it's macos only

2025-02-10 17:05 UTC, pbogut commented
> If anyone wants a workaround to get this feature you can try out my hotkeys config in the meantime which works good for me:
> 
> https://github.com/KorigamiK/zen-conf/blob/main/chrome/JS/hotkeys.uc.js

Does it need to be enabled somehow in zen in order to work? I've put file in place, cleared startup cache but it doesn't look like file is loaded at all. Cheers.

2025-02-10 18:10 UTC, KorigamiK commented
> > If anyone wants a workaround to get this feature you can try out my hotkeys config in the meantime which works good for me:
> > https://github.com/KorigamiK/zen-conf/blob/main/chrome/JS/hotkeys.uc.js
> 
> @KorigamiK Does it need to be enabled somehow in zen in order to work? I've put file in place, cleared startup cache but it doesn't look like file is loaded at all. Cheers.

No, you don't need to enable anything just place the files in the right locations.
See the [docs here](https://github.com/MrOtherGuy/fx-autoconfig?tab=readme-ov-file#setting-up-configjs-from-program-folder) which explains how to install fx-autoconfig, for me on linux using zen the directory path is `/opt/zen-browser-bin/defaults` but it might be different for you.

then you paste my script https://github.com/KorigamiK/zen-conf/blob/main/chrome/JS/hotkeys.uc.js into `chrome/JS/hotkeys.uc.js` in your profile folder.

2025-02-10 18:10 UTC, KorigamiK commented
> > If anyone wants a workaround to get this feature you can try out my hotkeys config in the meantime which works good for me:
> > https://github.com/KorigamiK/zen-conf/blob/main/chrome/JS/hotkeys.uc.js
> 
> @KorigamiK Does it need to be enabled somehow in zen in order to work? I've put file in place, cleared startup cache but it doesn't look like file is loaded at all. Cheers.

No, you don't need to enable anything just place the files in the right locations.
See the [docs here](https://github.com/MrOtherGuy/fx-autoconfig?tab=readme-ov-file#setting-up-configjs-from-program-folder) which explains how to install fx-autoconfig, for me on linux using zen the directory path is `/opt/zen-browser-bin/defaults` but it might be different for you.

then you paste my script https://github.com/KorigamiK/zen-conf/blob/main/chrome/JS/hotkeys.uc.js into `chrome/JS/hotkeys.uc.js` in your profile folder.

2025-03-25 17:41 UTC, dredstone1 commented
Any updates?

2025-03-27 08:29 UTC, tommerty commented
These buttons were initially here when I first discovered Zen many months ago, what caused the regression and the difficult re-implementation?

2025-04-12 16:24 UTC, wave84 commented
I'm also curious to know what's the issue here, this seemed like a simple change and at one point it worked fine, until it got removed.

2025-07-31 20:22 UTC, Ethnical commented
Up what we need to make this PR merged @mr-cheffy ?

2025-09-07 10:45 UTC, prwlr commented
Been following this issue quite closely for a while now. Not having this really breaks navigation with keyboard, especially once one includes PDF-viewer tabs, which Vimium can't navigate among. What contributions are currently missing @mr-cheffy ?

2025-09-18 13:44 UTC, kikefdezl commented
I must +1 this feature

I need to be able to remap Next/Previous tab cycling. The existing shortcuts:
- PgUp/PgDown are not available on some compact keyboards
- Ctrl+Tab and Ctrl+Shift+Tab are awkward to press

2025-09-18 22:11 UTC, normaltaro commented
I have not been using this browser since many months. I am glad and a bit overwhelmed to see such enthusiasm from so many people who are in support of this simple, yet extremely handy feature for keyboard-first users. I am not a legit programmer, though I wish to be.

From my understanding this browser code is a framework of patches onto firefox source code, like librewolf. I once browsed the firefox source code for `nexttab` and found this one easy ready to use function called `advanceSelectedTab()`.

I guessed that it might work with zen browsers codebase since I felt it lived in the same 'source-build scope' and I tried it.

It worked ok back then and I made this request. Another guy before me also made a request for this feature, and it wasnt merged. I cant recall why. I thought mine would be since the browser was in a very alpha state and changes I made were too tiny, not interfering with any development code. I should have referenced it when I posted this.

I think this wont be merged since the developers of the browser probably want to use their own 'framework' intead of this hacky one liner approach which directly calls a firefox internal browser function.

I do know a bit more programming now so I could try again to make a more 'real' patch with more consideration to workspace and split views behavior.
I might try again after I wake up today/tomorrow. **No guarantees**.

I will keep this request open since many people support it. Anyone is free to work on this feature and should not wait for me or this request.

I think should have sent this earlier but I am not too familiar with open source (or good at life in general). I am sorry.

2025-09-18 22:40 UTC, mr-cheffy commented
This should be moved into this newly created PR: https://github.com/zen-browser/desktop/pull/9441

The issue is mostly about how we should handle shortcuts and their precedence. It would be annoying if you tried to ctrl+tab and sites like github blocked that logic, right? So instead of using the firefox key management, we should be doing our own one. This is what firefox has done and why its hard coded. This however will be fixed very soon by disabling firefox's implementation and adding our own one that supports dynamic shortcuts.

2025-09-18 22:40 UTC, closed without merging